package Enum;

public enum NomesPessoas {
	LUCAS, CHASE, JOSH, NESSA, CHARLIE, ADDISON, LAURA, VINNIE, NOAH, JEREMIA, CONRAD, DAMON, STEFAN, LANADELREY,
	TAYLORSWIFT, SHAKIRA, HARRYPOTTER, HENRYDANGER, BATMAN, JOSE

}
