package Enum;

public enum ProdutosMercado {
	PAO, LEITE, FARINHA, QUEJO, PRESUNTO, CARNE, IOGURTE, CHOCOLATE, BALA, AZEITE, OLEO, ARROZ, FEIJAO, MACARRAO,
	BOLACHA, BATATA, BANANA, MORANGO, UVA, MELANCIA, ABOBORA, AGUA, SUCO, LARANJA, ALFACE, TOMATE, MILHO, CEREJA,
	CASTANHA, CAFE

}
